import type { CulturalTheme } from '../types/settings';

type ThemeVars = Record<string, string>;

type ThemeDefinition = {
  light: ThemeVars;
  dark: ThemeVars;
};

export type ThemeMeta = {
  id: CulturalTheme;
  name: string;
  meaning: string;
  gradient: [string, string];
  isPremium: boolean;
};

const shared = {
  '--acc-on-primary': '#ffffff',
};

const themes: Record<CulturalTheme, ThemeDefinition> = {
  harmattan: {
    light: {
      '--acc-bg': '#f4ecdf',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#d4a574',
      '--acc-accent': '#cd853f',
      '--acc-text': '#3f2b1d',
      '--acc-muted': '#7a5f4b',
      '--acc-border': '#ead9c6',
      ...shared,
    },
    dark: {
      '--acc-bg': '#2f241b',
      '--acc-surface': '#3a2c22',
      '--acc-primary': '#e6b98a',
      '--acc-accent': '#d69a5b',
      '--acc-text': '#f4e9dc',
      '--acc-muted': '#d1bca7',
      '--acc-border': '#4a372a',
      ...shared,
    },
  },
  hivernage: {
    light: {
      '--acc-bg': '#e7f3ea',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#4caf50',
      '--acc-accent': '#42a5f5',
      '--acc-text': '#1f3a2a',
      '--acc-muted': '#4b6b57',
      '--acc-border': '#d3e5d8',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1f2f26',
      '--acc-surface': '#26392f',
      '--acc-primary': '#66bb6a',
      '--acc-accent': '#64b5f6',
      '--acc-text': '#e6f3ea',
      '--acc-muted': '#b8d1c3',
      '--acc-border': '#2f4a3b',
      ...shared,
    },
  },
  sahel: {
    light: {
      '--acc-bg': '#FFF8E1',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#BF360C',
      '--acc-accent': '#FFD54F',
      '--acc-text': '#3E2723',
      '--acc-muted': '#8D6E63',
      '--acc-border': '#FFE082',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1B0D07',
      '--acc-surface': '#26140D',
      '--acc-primary': '#FF7043',
      '--acc-accent': '#FFD54F',
      '--acc-text': '#FFF8E1',
      '--acc-muted': '#BCAAA4',
      '--acc-border': '#3E2723',
      ...shared,
    },
  },
  nomad: {
    light: {
      '--acc-bg': '#D7CCC8',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#5D4037',
      '--acc-accent': '#BF360C',
      '--acc-text': '#3E2723',
      '--acc-muted': '#8D6E63',
      '--acc-border': '#BCAAA4',
      ...shared,
    },
    dark: {
      '--acc-bg': '#2D1D19',
      '--acc-surface': '#3D2B26',
      '--acc-primary': '#A1887F',
      '--acc-accent': '#FF7043',
      '--acc-text': '#D7CCC8',
      '--acc-muted': '#BCAAA4',
      '--acc-border': '#4E342E',
      ...shared,
    },
  },
  royal: {
    light: {
      '--acc-bg': '#f5f5f5',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#DAA520',
      '--acc-accent': '#DAA520',
      '--acc-text': '#121212',
      '--acc-muted': '#444444',
      '--acc-border': '#e0e0e0',
      ...shared,
    },
    dark: {
      '--acc-bg': '#121212',
      '--acc-surface': '#1a1a1a',
      '--acc-primary': '#FFD700',
      '--acc-accent': '#FFD700',
      '--acc-text': '#FFFFFF',
      '--acc-muted': '#AAAAAA',
      '--acc-border': '#333333',
      ...shared,
    },
  },
  fouta: {
    light: {
      '--acc-bg': '#E8F5E9',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#1B5E20',
      '--acc-accent': '#FFC107',
      '--acc-text': '#1B5E20',
      '--acc-muted': '#388E3C',
      '--acc-border': '#C8E6C9',
      ...shared,
    },
    dark: {
      '--acc-bg': '#0D2310',
      '--acc-surface': '#143319',
      '--acc-primary': '#66BB6A',
      '--acc-accent': '#FFC107',
      '--acc-text': '#E8F5E9',
      '--acc-muted': '#A5D6A7',
      '--acc-border': '#1B5E20',
      ...shared,
    },
  },
  pastoral: {
    light: {
      '--acc-bg': '#efebe9',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#8d6e63',
      '--acc-accent': '#03a9f4',
      '--acc-text': '#3e2723',
      '--acc-muted': '#6d4c41',
      '--acc-border': '#d7ccc8',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1b120f',
      '--acc-surface': '#2d1b16',
      '--acc-primary': '#a1887f',
      '--acc-accent': '#29b6f6',
      '--acc-text': '#efebe9',
      '--acc-muted': '#d7ccc8',
      '--acc-border': '#3e2723',
      ...shared,
    },
  },
  // --- New Android themes ---
  hootonde: {
    light: {
      '--acc-bg': '#e8eaf6',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#1a237e',
      '--acc-accent': '#ffd700',
      '--acc-text': '#1a237e',
      '--acc-muted': '#5c6bc0',
      '--acc-border': '#c5cae9',
      ...shared,
    },
    dark: {
      '--acc-bg': '#0d1033',
      '--acc-surface': '#141852',
      '--acc-primary': '#7986cb',
      '--acc-accent': '#ffd700',
      '--acc-text': '#e8eaf6',
      '--acc-muted': '#9fa8da',
      '--acc-border': '#283593',
      ...shared,
    },
  },
  nagge: {
    light: {
      '--acc-bg': '#efebe9',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#6d4c41',
      '--acc-accent': '#d7ccc8',
      '--acc-text': '#3e2723',
      '--acc-muted': '#8d6e63',
      '--acc-border': '#d7ccc8',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1b120f',
      '--acc-surface': '#2d1b16',
      '--acc-primary': '#a1887f',
      '--acc-accent': '#d7ccc8',
      '--acc-text': '#efebe9',
      '--acc-muted': '#bcaaa4',
      '--acc-border': '#4e342e',
      ...shared,
    },
  },
  lewru: {
    light: {
      '--acc-bg': '#e3f2fd',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#0d47a1',
      '--acc-accent': '#b0bec5',
      '--acc-text': '#0d47a1',
      '--acc-muted': '#42a5f5',
      '--acc-border': '#bbdefb',
      ...shared,
    },
    dark: {
      '--acc-bg': '#0a1929',
      '--acc-surface': '#0f2744',
      '--acc-primary': '#42a5f5',
      '--acc-accent': '#cfd8dc',
      '--acc-text': '#e3f2fd',
      '--acc-muted': '#90caf9',
      '--acc-border': '#1565c0',
      ...shared,
    },
  },
  naange: {
    light: {
      '--acc-bg': '#fff3e0',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#e65100',
      '--acc-accent': '#ffca28',
      '--acc-text': '#bf360c',
      '--acc-muted': '#ff9800',
      '--acc-border': '#ffe0b2',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a0e00',
      '--acc-surface': '#2d1800',
      '--acc-primary': '#ff9800',
      '--acc-accent': '#ffca28',
      '--acc-text': '#fff3e0',
      '--acc-muted': '#ffb74d',
      '--acc-border': '#e65100',
      ...shared,
    },
  },
  maayo: {
    light: {
      '--acc-bg': '#e0f7fa',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#006064',
      '--acc-accent': '#00bcd4',
      '--acc-text': '#004d40',
      '--acc-muted': '#26c6da',
      '--acc-border': '#b2ebf2',
      ...shared,
    },
    dark: {
      '--acc-bg': '#001a1d',
      '--acc-surface': '#002b31',
      '--acc-primary': '#26c6da',
      '--acc-accent': '#00bcd4',
      '--acc-text': '#e0f7fa',
      '--acc-muted': '#80deea',
      '--acc-border': '#00838f',
      ...shared,
    },
  },
  ladde: {
    light: {
      '--acc-bg': '#e8f5e9',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#2e7d32',
      '--acc-accent': '#795548',
      '--acc-text': '#1b5e20',
      '--acc-muted': '#66bb6a',
      '--acc-border': '#c8e6c9',
      ...shared,
    },
    dark: {
      '--acc-bg': '#0d1f10',
      '--acc-surface': '#14301a',
      '--acc-primary': '#66bb6a',
      '--acc-accent': '#a1887f',
      '--acc-text': '#e8f5e9',
      '--acc-muted': '#a5d6a7',
      '--acc-border': '#2e7d32',
      ...shared,
    },
  },
  wuro: {
    light: {
      '--acc-bg': '#fbe9e7',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#bf360c',
      '--acc-accent': '#f9a825',
      '--acc-text': '#3e2723',
      '--acc-muted': '#d84315',
      '--acc-border': '#ffccbc',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a0c08',
      '--acc-surface': '#2d1610',
      '--acc-primary': '#ff7043',
      '--acc-accent': '#f9a825',
      '--acc-text': '#fbe9e7',
      '--acc-muted': '#ff8a65',
      '--acc-border': '#bf360c',
      ...shared,
    },
  },
  pulaaku: {
    light: {
      '--acc-bg': '#f3e5f5',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#6a1b9a',
      '--acc-accent': '#ffd700',
      '--acc-text': '#4a148c',
      '--acc-muted': '#ab47bc',
      '--acc-border': '#e1bee7',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a0526',
      '--acc-surface': '#2a0d3d',
      '--acc-primary': '#ce93d8',
      '--acc-accent': '#ffd700',
      '--acc-text': '#f3e5f5',
      '--acc-muted': '#ba68c8',
      '--acc-border': '#6a1b9a',
      ...shared,
    },
  },
  kosam: {
    light: {
      '--acc-bg': '#fefefe',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#d7ccc8',
      '--acc-accent': '#bcaaa4',
      '--acc-text': '#5d4037',
      '--acc-muted': '#8d6e63',
      '--acc-border': '#efebe9',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1e1a18',
      '--acc-surface': '#2d2826',
      '--acc-primary': '#d7ccc8',
      '--acc-accent': '#bcaaa4',
      '--acc-text': '#efebe9',
      '--acc-muted': '#a1887f',
      '--acc-border': '#4e342e',
      ...shared,
    },
  },
  dental: {
    light: {
      '--acc-bg': '#fff3e0',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#ef6c00',
      '--acc-accent': '#ff9800',
      '--acc-text': '#e65100',
      '--acc-muted': '#fb8c00',
      '--acc-border': '#ffe0b2',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a0e00',
      '--acc-surface': '#2d1a00',
      '--acc-primary': '#ffa726',
      '--acc-accent': '#ff9800',
      '--acc-text': '#fff3e0',
      '--acc-muted': '#ffb74d',
      '--acc-border': '#ef6c00',
      ...shared,
    },
  },
  gorgal: {
    light: {
      '--acc-bg': '#fce4ec',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#b71c1c',
      '--acc-accent': '#212121',
      '--acc-text': '#b71c1c',
      '--acc-muted': '#e53935',
      '--acc-border': '#f8bbd0',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a0505',
      '--acc-surface': '#2d0a0a',
      '--acc-primary': '#ef5350',
      '--acc-accent': '#bdbdbd',
      '--acc-text': '#fce4ec',
      '--acc-muted': '#e57373',
      '--acc-border': '#c62828',
      ...shared,
    },
  },
  fooyre: {
    light: {
      '--acc-bg': '#fce4ec',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#c2185b',
      '--acc-accent': '#ffd700',
      '--acc-text': '#880e4f',
      '--acc-muted': '#ec407a',
      '--acc-border': '#f8bbd0',
      ...shared,
    },
    dark: {
      '--acc-bg': '#1a060e',
      '--acc-surface': '#2d0d1a',
      '--acc-primary': '#f06292',
      '--acc-accent': '#ffd700',
      '--acc-text': '#fce4ec',
      '--acc-muted': '#f48fb1',
      '--acc-border': '#c2185b',
      ...shared,
    },
  },
  hiirde: {
    light: {
      '--acc-bg': '#ede7f6',
      '--acc-surface': '#ffffff',
      '--acc-primary': '#4527a0',
      '--acc-accent': '#1a237e',
      '--acc-text': '#311b92',
      '--acc-muted': '#7e57c2',
      '--acc-border': '#d1c4e9',
      ...shared,
    },
    dark: {
      '--acc-bg': '#0d0726',
      '--acc-surface': '#1a0f3d',
      '--acc-primary': '#b39ddb',
      '--acc-accent': '#5c6bc0',
      '--acc-text': '#ede7f6',
      '--acc-muted': '#9575cd',
      '--acc-border': '#4527a0',
      ...shared,
    },
  },
};

/** Metadata for theme selector UI */
export const FREE_THEME_IDS = new Set<CulturalTheme>([
  'harmattan', 'hivernage', 'sahel', 'pastoral', 'fouta',
]);

export const themesMeta: ThemeMeta[] = [
  // Free themes (5)
  { id: 'harmattan', name: 'Harmattan', meaning: 'Vent sec', gradient: ['#d4a574', '#cd853f'], isPremium: false },
  { id: 'hivernage', name: 'Hivernage', meaning: 'Saison des pluies', gradient: ['#4caf50', '#42a5f5'], isPremium: false },
  { id: 'sahel', name: 'Sahel', meaning: 'Desert', gradient: ['#BF360C', '#FFD54F'], isPremium: false },
  { id: 'pastoral', name: 'Pastoral', meaning: 'Vie pastorale', gradient: ['#8d6e63', '#03a9f4'], isPremium: false },
  { id: 'fouta', name: 'Fouta', meaning: 'Vert traditionnel', gradient: ['#1B5E20', '#FFC107'], isPremium: false },
  // Premium themes (15)
  { id: 'hootonde', name: 'Hootonde', meaning: 'Nuit etoilee', gradient: ['#1a237e', '#ffd700'], isPremium: true },
  { id: 'nagge', name: 'Nagge', meaning: 'Betail sacre', gradient: ['#6d4c41', '#d7ccc8'], isPremium: true },
  { id: 'lewru', name: 'Lewru', meaning: 'Lune', gradient: ['#0d47a1', '#b0bec5'], isPremium: true },
  { id: 'naange', name: 'Naange', meaning: 'Lever du soleil', gradient: ['#e65100', '#ffca28'], isPremium: true },
  { id: 'maayo', name: 'Maayo', meaning: 'Riviere', gradient: ['#006064', '#00bcd4'], isPremium: true },
  { id: 'ladde', name: 'Ladde', meaning: 'Brousse', gradient: ['#2e7d32', '#795548'], isPremium: true },
  { id: 'wuro', name: 'Wuro', meaning: 'Village', gradient: ['#bf360c', '#f9a825'], isPremium: true },
  { id: 'pulaaku', name: 'Pulaaku', meaning: 'Code noble Peul', gradient: ['#6a1b9a', '#ffd700'], isPremium: true },
  { id: 'kosam', name: 'Kosam', meaning: 'Lait', gradient: ['#d7ccc8', '#efebe9'], isPremium: true },
  { id: 'dental', name: 'Dental', meaning: 'Famille', gradient: ['#ef6c00', '#ff9800'], isPremium: true },
  { id: 'gorgal', name: 'Gorgal', meaning: 'Esprit guerrier', gradient: ['#b71c1c', '#212121'], isPremium: true },
  { id: 'fooyre', name: 'Fooyre', meaning: 'Aube', gradient: ['#c2185b', '#ffd700'], isPremium: true },
  { id: 'hiirde', name: 'Hiirde', meaning: 'Contes du soir', gradient: ['#4527a0', '#1a237e'], isPremium: true },
  { id: 'royal', name: 'Royal', meaning: 'Or & Noir', gradient: ['#DAA520', '#121212'], isPremium: true },
  { id: 'nomad', name: 'Nomad', meaning: 'Tons terre', gradient: ['#5D4037', '#BF360C'], isPremium: true },
];

export const getThemeVars = (theme: CulturalTheme, isDarkMode: boolean): ThemeVars => {
  const selection = themes[theme] ?? themes.harmattan;
  return isDarkMode ? selection.dark : selection.light;
};
